#!/bin/bash -xe
tmp="$(mktemp /tmp/program.XXXXXX.cfg)"
exec 3>"$tmp"
rm "$tmp"

tmp="$(mktemp /tmp/program.XXXXXX.svf)"
exec 4>"$tmp"
rm "$tmp"

ecpunpack "$1" "/proc/$$/fd/3"
ecppack --svf "/proc/$$/fd/4" "/proc/$$/fd/3"

openocd -f "openocd.cfg" -c "svf -tap ecp5.tap -quiet -progress \"/proc/$$/fd/4\"; exit"
