#!/bin/bash -xe
tmp="$(mktemp /tmp/program.XXXXXX.svf)"
exec 3>"$tmp"
rm "$tmp"

fujprog -T bit -j sram -s "/proc/$$/fd/3" "$1"

openocd -f "openocd.cfg" -c "svf -tap ecp5.tap -quiet -progress \"/proc/$$/fd/3\"; exit"
